### ISSUE TITLE
Corrupt or missing JIRA information caused downtime

### ISSUE THREAD

**Issue by JoshRosen** [databricks/spark-pr-dashboard#44]
We had a bit of downtime last night, during which every request to `search_open_prs` was failing with the following stacktrace:

```python
Traceback (most recent call last):
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/lib/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/lib/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/lib/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/lib/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/lib/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/lib/flask_cache/__init__.py", line 297, in decorated_function
    rv = f(*args, **kwargs)
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/main.py", line 224, in search_open_prs
    d['jira_priority_name'] = first_jira.priority_name
  File "/base/data/home/apps/s~spark-prs/3.380963001868132083/sparkprs/models.py", line 276, in priority_name
    return self.issue_json["fields"]['priority']['name']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Perhaps there was a data inconsistency that caused this outage.  Things seem to have resolved themselves, but we should still fix this or add better error-handling to prevent this sort of issue from taking the whole site down.

**Comment by JoshRosen** [comment]
Uh oh, looks like this happened again. This time, I was able to figure out exactly when the error happened and managed to pull some more detailed logs for the last data ingest error before this started happening. It looks like we hit a timeout while updating a JIRA issue:

```
2015-12-30 15:03:14.016 /tasks/update-jira-issue/SPARK-12481 500 4997ms 0kb AppEngine-Google; (+http://code.google.com/appengine) module=default version=3
0.1.0.2 - - [30/Dec/2015:15:03:14 -0800] "POST /tasks/update-jira-issue/SPARK-12481 HTTP/1.1" 500 337 "http://spark-prs.appspot.com/tasks/update-jira-issues" "AppEngine-Google; (+http://code.google.com/appengine)" "spark-prs.appspot.com" ms=4997 cpu_ms=4 cpm_usd=0.000072 queue_name=jira-issues task_name=2210831314680575317 app_engine_release=1.9.30 trace_id=57c688a81d4f39ae3ccf77016929379c instance=00c61b117c5f549119ad423c256ba8e9c5f10396
D 2015-12-30 15:03:09.025
Updating JIRA issue SPARK-12481
E 2015-12-30 15:03:14.013
Exception on /tasks/update-jira-issue/SPARK-12481 [POST]
Traceback (most recent call last):
  File "/base/data/home/apps/s~spark-prs/3.389293730483239153/lib/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/s~spark-prs/3.389293730483239153/lib/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/base/data/home/apps/s~spark-prs/3.389293730483239153/lib/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/s~spark-prs/3.389293730483239153/lib/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~spark-prs/3.389293730483239153/lib/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~spark-prs/3.389293730483239153/sparkprs/controllers/tasks.py", line 247, in update_jira_issue
    JIRAIssue.get_or_create(issue_id).update()
  File "/base/data/home/apps/s~spark-prs/3.389293730483239153/sparkprs/models.py", line 260, in update
    self.issue_json = json.loads(urlfetch.fetch(url).content)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 271, in fetch
    return rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 428, in _get_fetch_result
    'Deadline exceeded while waiting for HTTP response from URL: ' + url)
DeadlineExceededError: Deadline exceeded while waiting for HTTP response from URL: https://issues.apache.org/jira/rest/api/latest/issue/SPARK-12481
```

**Comment by JoshRosen** [comment]
Added some logging and narrowed it down to https://github.com/apache/spark/pull/10205 causing this problem. 

It looks like some updates for this PR have been failing because SPARK-529 is in a reopened state, which prevents the bot from starting progress on that JIRA:

```
2015-12-30 15:26:08.013 /tasks/github/update-pr/10205 200 6226ms 0kb AppEngine-Google; (+http://code.google.com/appengine) module=default version=3
D 2015-12-30 15:26:01.790 Updating pull request 10205
I 2015-12-30 15:26:01.815 Requesting https://api.github.com/repos/apache/spark/pulls/10205 from GitHub with headers {'If-None-Match': u'W/"90a1b4b89ade821401217d2892f6d3bb"', '
I 2015-12-30 15:26:01.954 Starting new HTTPS connection (1): issues.apache.org
E 2015-12-30 15:26:07.140 Exception when linking to JIRA issue SPARK-529 Traceback (most recent call last): File "/base/data/home/apps/s~spark-prs/3.389293730483239153/sparkp
I 2015-12-30 15:26:07.149 Starting new HTTPS connection (1): issues.apache.org
D 2015-12-30 15:26:07.627 "GET /jira/rest/api/2/serverInfo HTTP/1.1" 200 None
D 2015-12-30 15:26:07.954 "GET /jira/rest/api/2/issue/SPARK-529 HTTP/1.1" 200 None
W 2015-12-30 15:26:07.958 Could not start progress on JIRA issue SPARK-529. It's currently in an 'Reopened' state. Issues must be in an 'Open' state.
```

**Comment by JoshRosen** [comment]
Aha! https://issues.apache.org/jira/browse/SPARK-529 does not have a priority!

**Comment by JoshRosen** [comment]
The priority field isn't missing, but its value is `null`:

```javascript
{
  "expand": "renderedFields,names,schema,transitions,operations,editmeta,changelog",
  "id": "12705320",
  "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/latest\/issue\/12705320",
  "key": "SPARK-529",
  "fields": {
    "issuetype": {
      "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issuetype\/4",
      "id": "4",
      "description": "An improvement or enhancement to an existing feature or task.",
      "iconUrl": "https:\/\/issues.apache.org\/jira\/images\/icons\/issuetypes\/improvement.png",
      "name": "Improvement",
      "subtask": false
    },
    "timespent": null,
    "project": {
      "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/project\/12315420",
      "id": "12315420",
      "key": "SPARK",
      "name": "Spark",
      "avatarUrls": {
        "48x48": "https:\/\/issues.apache.org\/jira\/secure\/projectavatar?pid=12315420&avatarId=19440",
        "24x24": "https:\/\/issues.apache.org\/jira\/secure\/projectavatar?size=small&pid=12315420&avatarId=19440",
        "16x16": "https:\/\/issues.apache.org\/jira\/secure\/projectavatar?size=xsmall&pid=12315420&avatarId=19440",
        "32x32": "https:\/\/issues.apache.org\/jira\/secure\/projectavatar?size=medium&pid=12315420&avatarId=19440"
      }
    },
    "fixVersions": [
      
    ],
    "aggregatetimespent": null,
    "resolution": null,
    "customfield_12312322": null,
    "customfield_12310220": "2012-10-19 18:03:00.0",
    "customfield_12312323": null,
    "customfield_12310420": "383671",
    "customfield_12312320": null,
    "customfield_12310222": null,
    "customfield_12312321": null,
    "customfield_12312120": null,
    "customfield_12312121": null,
    "resolutiondate": null,
    "workratio": -1,
    "customfield_12312328": null,
    "customfield_12312329": null,
    "customfield_12312326": null,
    "customfield_12310300": null,
    "customfield_12312327": null,
    "customfield_12312324": null,
    "customfield_12312325": null,
    "lastViewed": "2015-12-31T03:18:53.670+0000",
    "watches": {
      "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issue\/SPARK-529\/watchers",
      "watchCount": 5,
      "isWatching": false
    },
    "created": "0012-10-02T14:41:00.000+0000",
    "priority": null,
    "labels": [
      
    ],
    "customfield_12312333": null,
    "customfield_12312334": null,
    "customfield_12310310": "0.0",
    "customfield_12312331": null,
    "customfield_12312332": null,
    "timeestimate": null,
    "aggregatetimeoriginalestimate": null,
    "customfield_12312330": null,
    "customfield_12311120": null,
    "versions": [
      
    ],
    "issuelinks": [
      {
        "id": "12397313",
        "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issueLink\/12397313",
        "type": {
          "id": "10030",
          "name": "Reference",
          "inward": "is related to",
          "outward": "relates to",
          "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issueLinkType\/10030"
        },
        "outwardIssue": {
          "id": "12742992",
          "key": "SPARK-3620",
          "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issue\/12742992",
          "fields": {
            "summary": "Refactor config option handling code for spark-submit",
            "status": {
              "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/status\/3",
              "description": "This issue is being actively worked on at the moment by the assignee.",
              "iconUrl": "https:\/\/issues.apache.org\/jira\/images\/icons\/statuses\/inprogress.png",
              "name": "In Progress",
              "id": "3",
              "statusCategory": {
                "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/statuscategory\/4",
                "id": 4,
                "key": "indeterminate",
                "colorName": "yellow",
                "name": "In Progress"
              }
            },
            "priority": {
              "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/priority\/4",
              "iconUrl": "https:\/\/issues.apache.org\/jira\/images\/icons\/priorities\/minor.png",
              "name": "Minor",
              "id": "4"
            },
            "issuetype": {
              "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issuetype\/4",
              "id": "4",
              "description": "An improvement or enhancement to an existing feature or task.",
              "iconUrl": "https:\/\/issues.apache.org\/jira\/images\/icons\/issuetypes\/improvement.png",
              "name": "Improvement",
              "subtask": false
            }
          }
        }
      }
    ],
    "customfield_12312339": null,
    "assignee": null,
    "customfield_12312337": null,
    "customfield_12312338": null,
    "updated": "2015-12-30T23:01:27.710+0000",
    "customfield_12312335": null,
    "customfield_12312336": null,
    "customfield_12311720": null,
    "status": {
      "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/status\/4",
      "description": "This issue was once resolved, but the resolution was deemed incorrect. From here issues are either marked assigned or resolved.",
      "iconUrl": "https:\/\/issues.apache.org\/jira\/images\/icons\/statuses\/reopened.png",
      "name": "Reopened",
      "id": "4",
      "statusCategory": {
        "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/statuscategory\/2",
        "id": 2,
        "key": "new",
        "colorName": "blue-gray",
        "name": "New"
      }
    },
    "components": [
      
    ],
    "timeoriginalestimate": null,
    "description": "E.g. multiple places in the code base uses SPARK_MEM and has its own default set to 512. We need a central place to enforce default values as well as documenting the variables.",
    "customfield_10010": null,
    "timetracking": {
      
    },
    "customfield_12312026": null,
    "customfield_12312023": null,
    "customfield_12310320": null,
    "customfield_12312024": null,
    "customfield_12312340": null,
    "aggregatetimeestimate": null,
    "customfield_12312022": null,
    "customfield_12312341": null,
    "customfield_12312220": null,
    "customfield_12310921": null,
    "customfield_12310920": "383939",
    "summary": "Have a single file that controls the environmental variables and spark config options",
    "creator": null,
    "subtasks": [
      
    ],
    "customfield_12310291": null,
    "reporter": {
      "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/user?username=rxin",
      "name": "rxin",
      "emailAddress": "rxin at apache dot org",
      "avatarUrls": {
        "48x48": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?ownerId=rxin&avatarId=23451",
        "24x24": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=small&ownerId=rxin&avatarId=23451",
        "16x16": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=xsmall&ownerId=rxin&avatarId=23451",
        "32x32": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=medium&ownerId=rxin&avatarId=23451"
      },
      "displayName": "Reynold Xin",
      "active": true
    },
    "customfield_12310290": null,
    "aggregateprogress": {
      "progress": 0,
      "total": 0
    },
    "customfield_12311024": null,
    "environment": null,
    "customfield_12311020": null,
    "duedate": null,
    "customfield_12310250": null,
    "progress": {
      "progress": 0,
      "total": 0
    },
    "comment": {
      "startAt": 0,
      "maxResults": 3,
      "total": 3,
      "comments": [
        {
          "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issue\/12705320\/comment\/13952648",
          "id": "13952648",
          "author": {
            "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/user?username=patrick",
            "name": "patrick",
            "emailAddress": "patrick at cogan dot org dot uk",
            "avatarUrls": {
              "48x48": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?avatarId=10452",
              "24x24": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=small&avatarId=10452",
              "16x16": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=xsmall&avatarId=10452",
              "32x32": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=medium&avatarId=10452"
            },
            "displayName": "Patrick Cogan",
            "active": true
          },
          "body": "Imported from Github issue spark-239, originally reported by rxin",
          "updateAuthor": {
            "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/user?username=patrick",
            "name": "patrick",
            "emailAddress": "patrick at cogan dot org dot uk",
            "avatarUrls": {
              "48x48": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?avatarId=10452",
              "24x24": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=small&avatarId=10452",
              "16x16": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=xsmall&avatarId=10452",
              "32x32": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=medium&avatarId=10452"
            },
            "displayName": "Patrick Cogan",
            "active": true
          },
          "created": "2012-10-19T18:03:00.000+0000",
          "updated": "2012-10-19T18:03:00.000+0000"
        },
        {
          "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issue\/12705320\/comment\/14121138",
          "id": "14121138",
          "author": {
            "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/user?username=srowen",
            "name": "srowen",
            "emailAddress": "srowen at gmail dot com",
            "avatarUrls": {
              "48x48": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?ownerId=srowen&avatarId=10104",
              "24x24": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=small&ownerId=srowen&avatarId=10104",
              "16x16": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=xsmall&ownerId=srowen&avatarId=10104",
              "32x32": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=medium&ownerId=srowen&avatarId=10104"
            },
            "displayName": "Sean Owen",
            "active": true
          },
          "body": "This looks obsolete and\/or fixed, as variables like SPARK_MEM are deprecated, and I suppose there is spark-env.sh too.",
          "updateAuthor": {
            "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/user?username=srowen",
            "name": "srowen",
            "emailAddress": "srowen at gmail dot com",
            "avatarUrls": {
              "48x48": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?ownerId=srowen&avatarId=10104",
              "24x24": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=small&ownerId=srowen&avatarId=10104",
              "16x16": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=xsmall&ownerId=srowen&avatarId=10104",
              "32x32": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=medium&ownerId=srowen&avatarId=10104"
            },
            "displayName": "Sean Owen",
            "active": true
          },
          "created": "2014-09-04T08:54:08.730+0000",
          "updated": "2014-09-04T08:54:08.730+0000"
        },
        {
          "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issue\/12705320\/comment\/15075496",
          "id": "15075496",
          "author": {
            "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/user?username=vanzin",
            "name": "vanzin",
            "emailAddress": "vanzin+apache at cloudera dot com",
            "avatarUrls": {
              "48x48": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?avatarId=10452",
              "24x24": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=small&avatarId=10452",
              "16x16": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=xsmall&avatarId=10452",
              "32x32": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=medium&avatarId=10452"
            },
            "displayName": "Marcelo Vanzin",
            "active": true
          },
          "body": "I'm reopening this since I believe it's a worthy addition; in fact, Spark SQL already has something similar, and I'm just refactoring that code a little for use in the other modules.\r\n\r\n(It's not a single file per-se, but the spirit is the same - one location where a particular config option is defined - name, type and default value).",
          "updateAuthor": {
            "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/user?username=vanzin",
            "name": "vanzin",
            "emailAddress": "vanzin+apache at cloudera dot com",
            "avatarUrls": {
              "48x48": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?avatarId=10452",
              "24x24": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=small&avatarId=10452",
              "16x16": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=xsmall&avatarId=10452",
              "32x32": "https:\/\/issues.apache.org\/jira\/secure\/useravatar?size=medium&avatarId=10452"
            },
            "displayName": "Marcelo Vanzin",
            "active": true
          },
          "created": "2015-12-30T23:01:27.702+0000",
          "updated": "2015-12-30T23:01:27.702+0000"
        }
      ]
    },
    "votes": {
      "self": "https:\/\/issues.apache.org\/jira\/rest\/api\/2\/issue\/SPARK-529\/votes",
      "votes": 0,
      "hasVoted": false
    },
    "worklog": {
      "startAt": 0,
      "maxResults": 20,
      "total": 0,
      "worklogs": [
        
      ]
    },
    "customfield_12311820": "0|i1u3kn:",
    "customfield_12311620": null
  }
}
```
